repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: \.md$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [--extend-select, "I,RUF022", --fix, --ignore, E731]
        types_or: [python]
        files: ^agent/
        files: ^scripts/

      - id: ruff-format
        types_or: [python]
        files: ^agent/
        files: ^scripts/
