[general]
llm_model = "gpt-oss-20b"
llm_base_url = "http://localhost:8080/v1"
llm_reasoning = false
vlm_model = "lfm2-vl"
vlm_base_url = "http://localhost:8081/v1"
vlm_reasoning = false

# megamind agent utilizes llm for task delegation
# to agents using both llm and vlm for task execution
[megamind_agent]
llm_model = "gpt-oss-20b"
llm_base_url = "http://localhost:8080/v1"
vlm_model = "lfm2-vl"
vlm_base_url = "http://localhost:8081/v1"
llm_reasoning = false
vlm_reasoning = false

# inspection agent uses vlm to determine anomalies in the image
[inspection_agent]
vlm_model = "lfm2-vl"
vlm_base_url = "http://localhost:8081/v1"
vlm_reasoning = false
vlm_temperature = 0.0

[condition_agent]
vlm_model = "lfm2-vl"
vlm_base_url = "http://localhost:8081/v1"
vlm_reasoning = false
vlm_temperature = 0.1

# safety agent uses vlm to determine anomalies in the image
# and embeddings to determine OSHA safety violations
[safety_agent]
vlm_model = "lfm2-vl"
vlm_base_url = "http://localhost:8081/v1"
vlm_reasoning = false
vlm_temperature = 0.0

embeddings_model = "qwen3-embedding:0.6b"
embeddings_base_url = "http://localhost:8082/v1"
# NOTE: The reranker and the embedding model are two separate models!
reranker_base_url = "http://localhost:8083/v1/reranking"

# INFO:
# Start the EMBEDDING model in llama.cpp using the following command:
# ./llama-server -m /home/user/llamas/gguf/custom_ggufs/Qwen3-Embedding-0.6b_Q8_0.gguf --embedding --pooling last -c 4096 -b 2048 -ub 2048 --port 8082

# INFO:
# Start the RERANKER model in llama.cpp using the following command:
# ./llama-server -m /home/user/llamas/gguf/custom_ggufs/Qwen3-Reranker-0.6B_BF16.gguf --embedding --pooling rank -c 4096  -b 2048 -ub 2048 --port 8083
