FROM base_image

WORKDIR /root/MobileManipulatorDemo
ENV DEMO_ROOT=/root/MobileManipulatorDemo

COPY pixi.toml pixi.lock ./
COPY pyproject.toml uv.lock ./
COPY rai_app/ rai_app/
COPY scripts/ scripts/
COPY tests/ tests/
COPY regulations_db/ regulations_db/
COPY monitoring/ monitoring/
COPY config.toml ./

RUN pixi run sync
