FROM ros:jazzy-ros-core

RUN apt update && apt install -y \
    curl \
    python3-vcstool \
    git \
    git-lfs \
    ninja-build \
    ros-dev-tools

RUN curl -fsSL https://pixi.sh/install.sh | PIXI_HOME=/usr/local bash

WORKDIR /root/MobileManipulatorDemo
ENV DEMO_ROOT=/root/MobileManipulatorDemo

COPY pixi.toml pixi.lock pixi_activate.sh ros2_ws.repos ./

RUN rosdep init && pixi run build-ros2

RUN echo "source ${DEMO_ROOT}/ros2_ws/install/setup.bash" >> ~/.bashrc

RUN apt clean && rm -rf /var/lib/apt/lists/*
