ARG ROS2_IMAGE=robotecai/mobile-manipulator-demo-ros2:latest
FROM ${ROS2_IMAGE}

WORKDIR /root/MobileManipulatorDemo
ENV DEMO_ROOT=/root/MobileManipulatorDemo

# install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

COPY pyproject.toml ${DEMO_ROOT}
COPY rai_app/ ${DEMO_ROOT}/rai_app/
COPY scripts/ ${DEMO_ROOT}/scripts/
COPY tests/ ${DEMO_ROOT}/tests/
COPY regulations_db/ ${DEMO_ROOT}/regulations_db/
COPY monitoring/ ${DEMO_ROOT}/monitoring/
COPY config.toml ${DEMO_ROOT}

RUN uv sync
