<?xml version="1.0"?>
<package format="3">
  <name>mobile_manipulator_hmi</name>
  <version>0.0.1</version>
  <description>Simulation interface gui</description>
  <maintainer email="michal.pelka@robotec.ai">Micha&#x142; Pe&#x142;ka</maintainer>
  <license>Apache License 2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>rcl_interfaces</depend>
  <depend>tf2_ros</depend>
  <depend>tf2</depend>
  <depend>image_transport</depend>
  <depend>std_srvs</depend>
  <depend>cv_bridge</depend>
  <depend>robotec_kairos_ur10</depend>
  <exec_depend>qt5-qmake</exec_depend>
  <exec_depend>qtbase5-dev</exec_depend>
  <exec_depend>python3-psutil</exec_depend>
  <build_depend>demo_msgs</build_depend>
  <exec_depend>demo_msgs</exec_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
